-- ============================================================================
-- EFZ - Supabase / PostgreSQL Schema
-- File 18b : Website Request Inbox & Conversion
-- ----------------------------------------------------------------------------
-- Run AFTER 01..17 and 18a. Idempotent: safe to re-run. Apply to EFZ-Staging first.
-- Generated by make18.mjs from this template and the deployed definitions of
-- grant_role_preset() and guard_system_logs_insert() (Production backup
-- 20261008-144503Z); every change to those two is marked "18".
--
-- DESIGN: "EFZ Website Request Inbox & Conversion - Design" (approved 2026-10-08).
--
-- WHAT
--  new tables:  order_request_items (lines), order_request_notes (editable staff
--               notes), order_request_events (append-only timeline),
--               website_request_settings (1 row: limit + phone rules).
--  new columns: order_requests.assigned_to, status_changed_at, rejected_reason,
--               submission_key, phone_canonical (all nullable; no row rewritten).
--  new view:    order_request_lines (lines, or the legacy header product as line 1).
--  new functions: can_access_order_request, normalize_phone,
--               customer_phone_canonical, validate_request_phone,
--               website_request_lock_key, website_request_admission,
--               submit_order_request, set_order_request_status,
--               add_order_request_note, edit_order_request_note,
--               find_customers_by_phone, convert_website_request;
--               helpers guard_order_request_child (append-only lines/events),
--               website_request_settings_stamp; TEMPORARY until 18c:
--               order_requests_legacy_admission (+ 2 triggers).
--  changed:     order_requests_select policy (manage_website_requests or the
--               request's assignee); order_requests_update policy dropped;
--               grant_role_preset (Manager gains manage_website_requests);
--               guard_system_logs_insert (website-request audit lines are
--               database-only); anon keeps only INSERT on order_requests (until
--               18c); EXECUTE on convert_order_request revoked from authenticated;
--               order_requests added to supabase_realtime.
--  rows:        1 permissions row, 1 website_request_settings row, the new
--               permission granted to existing active Managers. No existing row is
--               updated or deleted; the existing requests are verified unchanged.
--
-- HARD BOUNDARIES (design K): no function here writes orders, order_items,
-- products, stock_movements, payments, commissions, order_deliveries or
-- below_cost_overrides. convert_website_request reaches orders only by calling
-- the unchanged create_order().
--
-- Rollback: supabase/rollback/18b_rollback.sql (after 18c's rollback, if 18c ran).
-- ============================================================================

begin;

set local lock_timeout = '30s';

-- ============================================================================
-- 0. PRE-GUARD: 18a present; the objects this file replaces are exactly the
--    reviewed Production definitions (first run) or this file's (re-run).
-- ============================================================================

do $pre$
declare
  v_labels   text[];
  v_cols     text;
  v_policies text;
  v_convert  text;
  v_preset   text;
  v_logs     text;
begin
  select array_agg(enumlabel::text order by enumsortorder) into v_labels
    from pg_enum where enumtypid = 'public.order_request_status'::regtype;
  if v_labels is distinct from array['new', 'contacted', 'confirmed', 'converted', 'rejected'] then
    raise exception '18b: run 18a first (order_request_status = %)', v_labels;
  end if;

  select string_agg(attname || ':' || format_type(atttypid, atttypmod), ',' order by attnum) into v_cols
    from pg_attribute where attrelid = 'public.order_requests'::regclass and attnum > 0 and not attisdropped;

  -- Role lists sorted: pg_dump/restore does not preserve their stored order.
  select string_agg(polname || ':' || md5(polcmd::text
           || (select string_agg(r::text, ',' order by r::text) from unnest(polroles::regrole[]) r)
           || coalesce(pg_get_expr(polqual, polrelid), '') || coalesce(pg_get_expr(polwithcheck, polrelid), '')),
         ';' order by polname) into v_policies
    from pg_policy where polrelid = 'public.order_requests'::regclass;

  v_convert := md5(pg_get_functiondef('public.convert_order_request(uuid, text)'::regprocedure));
  v_preset  := md5(pg_get_functiondef('public.grant_role_preset(text, public.user_role)'::regprocedure));
  v_logs    := md5(pg_get_functiondef('public.guard_system_logs_insert()'::regprocedure));

  if v_convert <> '@@MD5_CONVERT@@' then
    raise exception '18b: convert_order_request is not the reviewed definition (md5 %) - refusing', v_convert;
  end if;

  if md5(v_cols) = '@@MD5_COLS_PRE@@' and v_policies = '@@POLICIES_PRE@@'
     and v_preset = '@@MD5_PRESET_PRE@@' and v_logs = '@@MD5_LOGS_PRE@@' then
    raise notice '18b: reviewed Production state - applying';
  elsif md5(v_cols) = '@@MD5_COLS_POST@@' and v_policies = '@@POLICIES_POST@@'
     and v_preset = '@@MD5_PRESET_POST@@' and v_logs = '@@MD5_LOGS_POST@@' then
    raise notice '18b: already applied - re-applying (idempotent)';
  else
    raise exception '18b: unexpected state - refusing. columns md5 %, policies %, grant_role_preset md5 %, guard_system_logs_insert md5 %',
      md5(v_cols), v_policies, v_preset, v_logs;
  end if;
end
$pre$;

-- Every request that exists before this file runs, by its original columns.
-- Step 12 proves none of them was written.
create temp table m18_requests_before on commit drop as
  select r.id,
         md5(row(r.id, r.customer_name, r.phone, r.organization, r.product_id, r.product_name, r.quantity,
                 r.delivery_location, r.notes, r.status, r.converted_order_id, r.handled_by,
                 r.created_at, r.updated_at)::text) as row_md5
    from public.order_requests r;

-- ============================================================================
-- 1. COLUMNS ON order_requests (nullable, no default: existing rows unchanged)
-- ============================================================================

alter table public.order_requests add column if not exists assigned_to       text references public.profiles(id) on delete set null;
alter table public.order_requests add column if not exists status_changed_at timestamptz;
alter table public.order_requests add column if not exists rejected_reason   text;
alter table public.order_requests add column if not exists submission_key    uuid;
alter table public.order_requests add column if not exists phone_canonical   text;

do $con$
begin
  if not exists (select 1 from pg_constraint where conname = 'order_requests_rejected_reason_check') then
    alter table public.order_requests add constraint order_requests_rejected_reason_check
      check (rejected_reason is null or char_length(btrim(rejected_reason)) between 1 and 500);
  end if;
end
$con$;

create unique index if not exists order_requests_submission_key_uq
  on public.order_requests (submission_key) where submission_key is not null;
create unique index if not exists order_requests_converted_order_uq
  on public.order_requests (converted_order_id) where converted_order_id is not null;
create index if not exists idx_order_requests_new_by_phone
  on public.order_requests (phone_canonical, created_at) where status = 'new';

-- ============================================================================
-- 2. NEW TABLES
-- ============================================================================

create table if not exists public.order_request_items (
  id           uuid primary key default gen_random_uuid(),
  request_id   uuid not null references public.order_requests(id) on delete cascade,
  line_no      integer not null check (line_no between 1 and 20),
  product_id   text references public.products(id) on delete set null,
  product_name text not null check (char_length(btrim(product_name)) between 1 and 200),
  quantity     integer not null check (quantity between 1 and 100000),
  created_at   timestamptz not null default now(),
  unique (request_id, line_no)
);

create table if not exists public.order_request_notes (
  id          uuid primary key default gen_random_uuid(),
  request_id  uuid not null references public.order_requests(id) on delete cascade,
  body        text not null check (char_length(btrim(body)) between 1 and 2000),
  author_id   text references public.profiles(id) on delete set null,
  author_name text not null default '',
  edited_by   text references public.profiles(id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists order_request_notes_request_idx on public.order_request_notes (request_id, created_at);

create table if not exists public.order_request_events (
  id          uuid primary key default gen_random_uuid(),
  seq         bigint generated always as identity,
  request_id  uuid not null references public.order_requests(id) on delete cascade,
  event       text not null check (event in ('submitted', 'status_changed', 'converted', 'note_added', 'note_edited')),
  source      text check (source in ('rpc', 'legacy_direct')),
  from_status text,
  to_status   text,
  actor_id    text references public.profiles(id) on delete set null,
  actor_name  text not null default '',
  order_id    text,   -- no FK: the trace survives if the order is ever deleted
  note        text,
  details     jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);
create index if not exists order_request_events_request_idx on public.order_request_events (request_id, seq);

create table if not exists public.website_request_settings (
  id                    boolean primary key default true check (id),
  max_new_per_phone     integer not null default 3 check (max_new_per_phone between 1 and 100),
  window_hours          integer not null default 24 check (window_hours between 1 and 720),
  limit_enabled         boolean not null default true,
  default_phone_country text not null default 'SO' check (default_phone_country in ('SO')),
  so_leading_digits     text not null default '679' check (so_leading_digits ~ '^[1-9]{1,9}$'),
  accept_international  boolean not null default false,
  updated_by            text references public.profiles(id) on delete set null,
  updated_at            timestamptz not null default now()
);
insert into public.website_request_settings (id) values (true) on conflict (id) do nothing;

-- Lines and events are append-only; notes may be edited (through the RPC) but not
-- deleted. A row may only disappear with its request (FK cascade).
create or replace function public.guard_order_request_child()
returns trigger
language plpgsql
set search_path = public
as $fn$
begin
  if tg_op = 'UPDATE' then
    raise exception '% rows are append-only and cannot be changed', tg_table_name using errcode = '42501';
  end if;
  if exists (select 1 from public.order_requests r where r.id = old.request_id) then
    raise exception '% rows cannot be deleted', tg_table_name using errcode = '42501';
  end if;
  return old;
end;
$fn$;

drop trigger if exists trg_order_request_items_guard on public.order_request_items;
create trigger trg_order_request_items_guard
  before update or delete on public.order_request_items
  for each row execute function public.guard_order_request_child();

drop trigger if exists trg_order_request_events_guard on public.order_request_events;
create trigger trg_order_request_events_guard
  before update or delete on public.order_request_events
  for each row execute function public.guard_order_request_child();

drop trigger if exists trg_order_request_notes_guard on public.order_request_notes;
create trigger trg_order_request_notes_guard
  before delete on public.order_request_notes
  for each row execute function public.guard_order_request_child();

create or replace function public.website_request_settings_stamp()
returns trigger
language plpgsql
set search_path = public
as $fn$
begin
  new.id         := true;
  new.updated_at := now();
  new.updated_by := public.current_profile_id();
  return new;
end;
$fn$;

drop trigger if exists trg_website_request_settings_stamp on public.website_request_settings;
create trigger trg_website_request_settings_stamp
  before update on public.website_request_settings
  for each row execute function public.website_request_settings_stamp();

-- ============================================================================
-- 3. ACCESS RULE AND PHONE FUNCTIONS
-- ============================================================================

-- The one rule for reading and working a request: the request permission, or
-- (future) being the request's assignee. assigned_to stays NULL in v1.
create or replace function public.can_access_order_request(p_assigned_to text)
returns boolean
language sql
stable
security definer
set search_path = public
as $fn$
  select public.has_permission('manage_website_requests')
      or (p_assigned_to is not null and p_assigned_to = public.current_profile_id());
$fn$;

-- Pure canonicalization to E.164 ('+252612345678'), or NULL. p_country decides
-- only how a number WITHOUT an international prefix is read; v1 implements SO.
create or replace function public.normalize_phone(p_raw text, p_country text default 'SO')
returns text
language plpgsql
immutable
set search_path = public
as $fn$
declare
  s text;
  d text;
begin
  if p_raw is null then
    return null;
  end if;
  s := regexp_replace(btrim(p_raw), '[[:space:]().-]', '', 'g');
  if s !~ '^\+?[0-9]+$' then
    return null;
  end if;
  if s like '00%' then
    s := '+' || substr(s, 3);
  end if;

  if s like '+%' then
    d := substr(s, 2);
    if d like '252%' then
      return case when d ~ '^252[1-9][0-9]{8}$' then '+' || d end;   -- SO: 9-digit national number
    end if;
    return case when d ~ '^[1-9][0-9]{7,14}$' then '+' || d end;     -- other E.164: 8-15 digits
  end if;

  if p_country = 'SO' then
    if s ~ '^252[1-9][0-9]{8}$' then return '+' || s; end if;         -- 252612345678
    if s ~ '^0[1-9][0-9]{8}$'   then return '+252' || substr(s, 2); end if;  -- 0612345678
    if s ~ '^[1-9][0-9]{8}$'    then return '+252' || s; end if;      -- 612345678
  end if;
  return null;
end;
$fn$;

-- EFZ's storage convention for customers.phone: a national number is Somali; a
-- number stored with '+' is read as written. Backs the customer match index, and
-- deliberately does NOT read the input-default setting.
create or replace function public.customer_phone_canonical(p_phone text)
returns text
language sql
immutable
set search_path = public
as $fn$
  select public.normalize_phone(p_phone, 'SO');
$fn$;

create index if not exists idx_customers_phone_canonical
  on public.customers (public.customer_phone_canonical(phone));

-- The accepted-format policy (website_request_settings). Returns the canonical
-- number or refuses with WR422.
create or replace function public.validate_request_phone(p_raw text)
returns text
language plpgsql
stable
security definer
set search_path = public
as $fn$
declare
  s public.website_request_settings%rowtype;
  c text;
begin
  select * into s from public.website_request_settings where id;
  c := public.normalize_phone(p_raw, coalesce(s.default_phone_country, 'SO'));
  if c is not null then
    if c like '+252%' then
      if position(substr(c, 5, 1) in coalesce(s.so_leading_digits, '679')) > 0 then
        return c;
      end if;
    elsif coalesce(s.accept_international, false) then
      return c;
    end if;
  end if;
  raise exception 'Please enter a valid Somali phone number, e.g. 061 234 5678'
    using errcode = 'WR422';
end;
$fn$;

-- 32-bit key for the per-phone advisory lock pg_advisory_xact_lock(1818, key).
-- Class id 1818 is reserved for website requests; the two-integer key space never
-- overlaps the single-bigint one used by the commission-eligibility lock.
create or replace function public.website_request_lock_key(p_canonical text)
returns integer
language sql
immutable
set search_path = public
as $fn$
  select hashtext('efz-website-request:' || coalesce(p_canonical, ''));
$fn$;

-- Admission for BOTH submit paths. VOLATILE on purpose: every statement takes a
-- fresh READ COMMITTED snapshot after the lock, so it sees every earlier commit
-- for this phone. Returns the existing request id for a repeated submission key.
create or replace function public.website_request_admission(p_canonical text, p_submission_key uuid default null)
returns uuid
language plpgsql
volatile
security definer
set search_path = public
as $fn$
declare
  s          public.website_request_settings%rowtype;
  v_count    integer;
  v_existing uuid;
begin
  if current_setting('transaction_isolation') <> 'read committed' then
    raise exception 'Website request admission requires READ COMMITTED isolation (got %)',
      current_setting('transaction_isolation') using errcode = 'WR500';
  end if;

  perform pg_advisory_xact_lock(1818, public.website_request_lock_key(p_canonical));

  if p_submission_key is not null then
    select r.id into v_existing from public.order_requests r where r.submission_key = p_submission_key;
    if found then
      return v_existing;
    end if;
  end if;

  select * into s from public.website_request_settings where id;
  if coalesce(s.limit_enabled, true) then
    select count(*) into v_count
      from public.order_requests r
     where r.phone_canonical = p_canonical
       and r.status = 'new'
       and r.created_at > now() - make_interval(hours => coalesce(s.window_hours, 24));
    if v_count >= coalesce(s.max_new_per_phone, 3) then
      raise exception 'We already have your recent requests and will contact you shortly.'
        using errcode = 'WR429';
    end if;
  end if;
  return null;
end;
$fn$;

-- ============================================================================
-- 4. PUBLIC SUBMISSION
-- ============================================================================

create or replace function public.submit_order_request(p_payload jsonb)
returns uuid
language plpgsql
volatile
security definer
set search_path = public
as $fn$
declare
  v_name     text := btrim(coalesce(p_payload ->> 'customerName', ''));
  v_phone    text := btrim(coalesce(p_payload ->> 'phone', ''));
  v_org      text := btrim(coalesce(p_payload ->> 'organization', ''));
  v_location text := btrim(coalesce(p_payload ->> 'deliveryLocation', ''));
  v_notes    text := btrim(coalesce(p_payload ->> 'notes', ''));
  v_lines    jsonb := p_payload -> 'lines';
  v_key      uuid;
  v_canon    text;
  v_existing uuid;
  v_id       uuid := gen_random_uuid();
  v_line     jsonb;
  v_seq      integer := 0;
  v_units    integer := 0;
  v_qty_raw  numeric;
  v_product  public.products%rowtype;
  v_seen     text[] := '{}';
  v_names    text[] := '{}';
  v_qtys     integer[] := '{}';
begin
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception 'Invalid request' using errcode = '22023';
  end if;
  if char_length(v_name) not between 1 and 200 then
    raise exception 'Please enter your name (up to 200 characters)' using errcode = '22023';
  end if;
  if char_length(v_phone) not between 1 and 50 then
    raise exception 'Please enter a valid Somali phone number, e.g. 061 234 5678' using errcode = 'WR422';
  end if;
  if char_length(v_org) > 200 or char_length(v_location) > 500 or char_length(v_notes) > 2000 then
    raise exception 'A field is too long' using errcode = '22023';
  end if;
  if jsonb_typeof(v_lines) is distinct from 'array' or jsonb_array_length(v_lines) not between 1 and 20 then
    raise exception 'A request needs between 1 and 20 products' using errcode = '22023';
  end if;
  begin
    v_key := nullif(p_payload ->> 'submissionKey', '')::uuid;
  exception when invalid_text_representation then
    raise exception 'Invalid submission key' using errcode = '22023';
  end;

  v_canon := public.validate_request_phone(v_phone);
  v_existing := public.website_request_admission(v_canon, v_key);
  if v_existing is not null then
    return v_existing;   -- the same form submitted again: nothing new is written
  end if;

  -- Validate every line before anything is written.
  for v_line in select * from jsonb_array_elements(v_lines)
  loop
    select * into v_product from public.products p
     where p.id = v_line ->> 'productId' and p.is_active;
    if not found then
      raise exception 'A selected product is not available' using errcode = '22023';
    end if;
    if v_product.id = any (v_seen) then
      raise exception 'Each product can be listed once; change its quantity instead' using errcode = '22023';
    end if;
    begin
      v_qty_raw := (v_line ->> 'quantity')::numeric;
    exception when invalid_text_representation then
      v_qty_raw := null;
    end;
    if v_qty_raw is null or v_qty_raw <> trunc(v_qty_raw) or v_qty_raw not between 1 and 100000 then
      raise exception 'Quantity must be a whole number between 1 and 100000' using errcode = '22023';
    end if;
    v_seen  := v_seen || v_product.id;
    v_names := v_names || v_product.name;
    v_qtys  := v_qtys || v_qty_raw::integer;
    v_units := v_units + v_qty_raw::integer;
  end loop;

  -- Marks THIS insert for the temporary legacy-path trigger, and only this one:
  -- cleared straight after, so no later direct insert in the same transaction
  -- can pass as an RPC insert.
  perform set_config('efz.website_request_rpc', 'on', true);

  -- The header mirrors line 1 in the legacy columns, for old exports and readers.
  insert into public.order_requests (id, customer_name, phone, organization, product_id, product_name, quantity,
                                     delivery_location, notes, status, submission_key, phone_canonical)
  values (v_id, v_name, v_phone, v_org, v_seen[1], v_names[1], v_qtys[1], v_location, v_notes, 'new', v_key, v_canon);

  perform set_config('efz.website_request_rpc', '', true);

  for v_seq in 1 .. cardinality(v_seen)
  loop
    insert into public.order_request_items (request_id, line_no, product_id, product_name, quantity)
    values (v_id, v_seq, v_seen[v_seq], v_names[v_seq], v_qtys[v_seq]);
  end loop;
  v_seq := cardinality(v_seen);

  insert into public.order_request_events (request_id, event, source, to_status, actor_id, actor_name, details)
  values (v_id, 'submitted', 'rpc', 'new', public.current_profile_id(), coalesce(public.current_profile_name(), ''),
          jsonb_build_object('lines', v_seq, 'units', v_units));

  insert into public.system_logs (id, severity, category, message, user_id, username, target_id, metadata)
  values ('log-' || replace(gen_random_uuid()::text, '-', ''), 'INFO', 'ORDER',
          format('Website request REQ-%s received: %s item(s), %s unit(s)',
                 upper(left(replace(v_id::text, '-', ''), 8)), v_seq, v_units),
          public.current_profile_id(), coalesce(public.current_profile_name(), ''), v_id::text,
          jsonb_build_object('source', 'db', 'event', 'website_request_submitted', 'requestId', v_id,
                             'path', 'rpc', 'lines', v_seq, 'units', v_units));
  return v_id;
end;
$fn$;

-- TEMPORARY (dropped by 18c): the old /order page inserts straight into
-- order_requests. Until 18c removes that path, hold it to the same phone rules,
-- limit and lock as submit_order_request, and record it in the timeline/audit.
-- SECURITY DEFINER, so it detects a direct client insert by the PostgREST role
-- setting (anon/authenticated) without the RPC's transaction flag.
create or replace function public.order_requests_legacy_admission()
returns trigger
language plpgsql
volatile
security definer
set search_path = public
as $fn$
declare
  v_canon text;
begin
  if coalesce(current_setting('role', true), 'none') not in ('anon', 'authenticated')
     or coalesce(current_setting('efz.website_request_rpc', true), '') = 'on' then
    return case when tg_when = 'BEFORE' then new else null end;
  end if;

  if tg_when = 'BEFORE' then
    v_canon := public.validate_request_phone(new.phone);
    perform public.website_request_admission(v_canon, null);
    new.phone_canonical   := v_canon;
    new.submission_key    := null;   -- a direct insert never sets the new columns
    new.assigned_to       := null;
    new.status_changed_at := null;
    new.rejected_reason   := null;
    return new;
  end if;

  insert into public.order_request_events (request_id, event, source, to_status, actor_id, actor_name, details)
  values (new.id, 'submitted', 'legacy_direct', 'new', public.current_profile_id(),
          coalesce(public.current_profile_name(), ''), jsonb_build_object('lines', 1, 'units', new.quantity));

  insert into public.system_logs (id, severity, category, message, user_id, username, target_id, metadata)
  values ('log-' || replace(gen_random_uuid()::text, '-', ''), 'INFO', 'ORDER',
          format('Website request REQ-%s received: 1 item(s), %s unit(s)',
                 upper(left(replace(new.id::text, '-', ''), 8)), new.quantity),
          public.current_profile_id(), coalesce(public.current_profile_name(), ''), new.id::text,
          jsonb_build_object('source', 'db', 'event', 'website_request_submitted', 'requestId', new.id,
                             'path', 'legacy_direct', 'lines', 1, 'units', new.quantity));
  return null;
end;
$fn$;

drop trigger if exists trg_order_requests_legacy_admission on public.order_requests;
create trigger trg_order_requests_legacy_admission
  before insert on public.order_requests
  for each row execute function public.order_requests_legacy_admission();

drop trigger if exists trg_order_requests_legacy_admission_after on public.order_requests;
create trigger trg_order_requests_legacy_admission_after
  after insert on public.order_requests
  for each row execute function public.order_requests_legacy_admission();

-- ============================================================================
-- 5. STAFF WORKFLOW
-- ============================================================================

create or replace function public.set_order_request_status(p_request_id uuid, p_to text, p_reason text default null)
returns void
language plpgsql
volatile
security definer
set search_path = public
as $fn$
declare
  v_req    public.order_requests%rowtype;
  v_reason text := nullif(btrim(coalesce(p_reason, '')), '');
  v_label  text;
  v_msg    text;
begin
  select * into v_req from public.order_requests where id = p_request_id for update;
  if not found or not public.can_access_order_request(v_req.assigned_to) then
    raise exception 'Permission denied or unknown website request' using errcode = '42501';
  end if;

  if p_to = 'converted' then
    raise exception 'A request is converted only with Convert to Order' using errcode = 'WR409';
  end if;
  if (v_req.status::text, p_to) not in (('new', 'contacted'), ('new', 'confirmed'), ('new', 'rejected'),
                                        ('contacted', 'confirmed'), ('contacted', 'rejected'),
                                        ('confirmed', 'rejected')) then
    raise exception 'A % request cannot be marked %', v_req.status, p_to using errcode = 'WR409';
  end if;
  if p_to = 'rejected' and (v_reason is null or char_length(v_reason) > 500) then
    raise exception 'A reason (up to 500 characters) is required to reject a request' using errcode = '22023';
  end if;

  update public.order_requests
     set status            = p_to::public.order_request_status,
         status_changed_at = now(),
         handled_by        = public.current_profile_id(),
         rejected_reason   = case when p_to = 'rejected' then v_reason else rejected_reason end,
         updated_at        = now()
   where id = p_request_id;

  insert into public.order_request_events (request_id, event, from_status, to_status, actor_id, actor_name, note)
  values (p_request_id, 'status_changed', v_req.status::text, p_to, public.current_profile_id(),
          coalesce(public.current_profile_name(), ''), v_reason);

  v_label := 'REQ-' || upper(left(replace(p_request_id::text, '-', ''), 8));
  v_msg := case p_to
             when 'contacted' then format('Website request %s marked contacted', v_label)
             when 'confirmed' then format('Website request %s confirmed (from %s)', v_label, v_req.status)
             else format('Website request %s rejected (reason recorded on the request)', v_label)
           end;
  insert into public.system_logs (id, severity, category, message, user_id, username, target_id, metadata)
  values ('log-' || replace(gen_random_uuid()::text, '-', ''), 'INFO', 'ORDER', v_msg,
          public.current_profile_id(), coalesce(public.current_profile_name(), ''), p_request_id::text,
          jsonb_build_object('source', 'db', 'event', 'website_request_status', 'requestId', p_request_id,
                             'fromStatus', v_req.status, 'toStatus', p_to));
end;
$fn$;

create or replace function public.add_order_request_note(p_request_id uuid, p_body text)
returns uuid
language plpgsql
volatile
security definer
set search_path = public
as $fn$
declare
  v_req  public.order_requests%rowtype;
  v_body text := btrim(coalesce(p_body, ''));
  v_id   uuid;
begin
  select * into v_req from public.order_requests where id = p_request_id;
  if not found or not public.can_access_order_request(v_req.assigned_to) then
    raise exception 'Permission denied or unknown website request' using errcode = '42501';
  end if;
  if char_length(v_body) not between 1 and 2000 then
    raise exception 'A note must be 1 to 2000 characters' using errcode = '22023';
  end if;

  insert into public.order_request_notes (request_id, body, author_id, author_name)
  values (p_request_id, v_body, public.current_profile_id(), coalesce(public.current_profile_name(), ''))
  returning id into v_id;

  insert into public.order_request_events (request_id, event, actor_id, actor_name, details)
  values (p_request_id, 'note_added', public.current_profile_id(), coalesce(public.current_profile_name(), ''),
          jsonb_build_object('noteId', v_id));
  return v_id;
end;
$fn$;

-- Author (while they can still access the request) or the Super Admin. The
-- previous text is kept in the timeline.
create or replace function public.edit_order_request_note(p_note_id uuid, p_body text)
returns void
language plpgsql
volatile
security definer
set search_path = public
as $fn$
declare
  v_note public.order_request_notes%rowtype;
  v_req  public.order_requests%rowtype;
  v_body text := btrim(coalesce(p_body, ''));
begin
  select * into v_note from public.order_request_notes where id = p_note_id for update;
  if found then
    select * into v_req from public.order_requests where id = v_note.request_id;
  end if;
  if not found
     or not public.can_access_order_request(v_req.assigned_to)
     or not (public.is_super_admin() or v_note.author_id = public.current_profile_id()) then
    raise exception 'Permission denied or unknown note' using errcode = '42501';
  end if;
  if char_length(v_body) not between 1 and 2000 then
    raise exception 'A note must be 1 to 2000 characters' using errcode = '22023';
  end if;
  if v_body = v_note.body then
    return;
  end if;

  update public.order_request_notes
     set body = v_body, edited_by = public.current_profile_id(), updated_at = now()
   where id = p_note_id;

  insert into public.order_request_events (request_id, event, actor_id, actor_name, details)
  values (v_note.request_id, 'note_edited', public.current_profile_id(), coalesce(public.current_profile_name(), ''),
          jsonb_build_object('noteId', p_note_id, 'previous', v_note.body));
end;
$fn$;

-- Match candidates for conversion, by canonical phone. Request handlers only
-- (never the future assignee: it searches all customers).
create or replace function public.find_customers_by_phone(p_request_id uuid, p_phone text default null)
returns table (customer_id text, name text, phone_masked text, officer_id text, officer_name text, status text)
language plpgsql
stable
security definer
set search_path = public
as $fn$
declare
  v_req   public.order_requests%rowtype;
  v_canon text;
begin
  if not public.has_permission('manage_website_requests') then
    raise exception 'Permission denied: website requests' using errcode = '42501';
  end if;
  select * into v_req from public.order_requests where id = p_request_id;
  if not found then
    raise exception 'Permission denied or unknown website request' using errcode = '42501';
  end if;

  v_canon := case
               when nullif(btrim(coalesce(p_phone, '')), '') is not null
                 then public.normalize_phone(p_phone,
                        coalesce((select default_phone_country from public.website_request_settings where id), 'SO'))
               else coalesce(v_req.phone_canonical, public.normalize_phone(v_req.phone, 'SO'))
             end;
  if v_canon is null then
    return;
  end if;

  return query
    select c.id, c.name,
           case when char_length(c.phone) > 3 then repeat('*', char_length(c.phone) - 3) || right(c.phone, 3) else '***' end,
           c.marketing_officer_id, coalesce(p.name, ''), c.status::text
      from public.customers c
      left join public.profiles p on p.id = c.marketing_officer_id
     where public.customer_phone_canonical(c.phone) = v_canon
     order by (c.status = 'active') desc, c.name;
end;
$fn$;

-- ============================================================================
-- 6. CONVERSION: customer (existing or new, optional initial owner) + the
--    unchanged create_order() + link, in one transaction.
-- ============================================================================

create or replace function public.convert_website_request(p_request_id uuid, p_payload jsonb)
returns text
language plpgsql
volatile
security definer
set search_path = public
as $fn$
declare
  v_req         public.order_requests%rowtype;
  v_actor       text := public.current_profile_id();
  v_actor_name  text := coalesce(public.current_profile_name(), '');
  v_label       text := 'REQ-' || upper(left(replace(p_request_id::text, '-', ''), 8));
  v_lines       jsonb := p_payload -> 'lines';
  v_new         jsonb := p_payload -> 'newCustomer';
  v_customer_id text := nullif(btrim(coalesce(p_payload ->> 'customerId', '')), '');
  v_owner_id    text;
  v_owner       public.profiles%rowtype;
  v_items       jsonb := '[]'::jsonb;
  v_line        jsonb;
  v_name        text;
  v_phone_raw   text;
  v_canon       text;
  v_stored      text;
  v_new_cust    boolean := false;
  v_order_id    text;
begin
  select * into v_req from public.order_requests where id = p_request_id for update;
  if not found or not public.can_access_order_request(v_req.assigned_to) then
    raise exception 'Permission denied or unknown website request' using errcode = '42501';
  end if;

  if v_req.status = 'converted' then
    raise exception 'Website request % was already converted to order %', v_label, v_req.converted_order_id
      using errcode = 'WR409';
  end if;
  if v_req.status <> 'confirmed' then
    raise exception 'Only a confirmed request can be converted (this one is %)', v_req.status using errcode = 'WR409';
  end if;

  if jsonb_typeof(v_lines) is distinct from 'array' or jsonb_array_length(v_lines) not between 1 and 20 then
    raise exception 'A conversion needs between 1 and 20 lines' using errcode = '22023';
  end if;
  for v_line in select * from jsonb_array_elements(v_lines)
  loop
    if nullif(v_line ->> 'productId', '') is null or (v_line -> 'actualUnitPrice') is null
       or jsonb_typeof(v_line -> 'actualUnitPrice') <> 'number' then
      raise exception 'Every line needs a product and a confirmed unit price' using errcode = '22023';
    end if;
    v_items := v_items || jsonb_build_array(jsonb_build_object(
                 'productId', v_line ->> 'productId',
                 'quantity', v_line -> 'quantity',
                 'actualUnitPrice', v_line -> 'actualUnitPrice'));
  end loop;

  if (v_customer_id is null) = (v_new is null or jsonb_typeof(v_new) <> 'object') then
    raise exception 'Choose an existing customer or a new one' using errcode = '22023';
  end if;

  if v_customer_id is not null then
    if nullif(btrim(coalesce(p_payload ->> 'ownerOfficerId', v_new ->> 'ownerOfficerId', '')), '') is not null then
      raise exception 'An existing customer keeps its owner; ownership changes only with a customer transfer'
        using errcode = '22023';
    end if;
  else
    v_new_cust := true;
    if not public.has_permission('add_customers') then
      raise exception 'Permission denied: add_customers is required to create a customer' using errcode = '42501';
    end if;
    v_name := btrim(coalesce(v_new ->> 'name', ''));
    if char_length(v_name) not between 1 and 200 then
      raise exception 'The new customer needs a name (up to 200 characters)' using errcode = '22023';
    end if;
    v_phone_raw := btrim(coalesce(v_new ->> 'phone', ''));
    v_canon := public.validate_request_phone(v_phone_raw);

    if exists (select 1 from public.customers c where public.customer_phone_canonical(c.phone) = v_canon)
       and coalesce((p_payload ->> 'confirmNoDuplicate')::boolean, false) is not true then
      raise exception 'A customer with this phone already exists: pick it, or confirm a separate customer'
        using errcode = 'WR410';
    end if;

    v_owner_id := nullif(btrim(coalesce(v_new ->> 'ownerOfficerId', '')), '');
    if v_owner_id is not null then
      if not public.has_permission('manage_website_requests') then
        raise exception 'Permission denied: only a request handler can set the initial owner' using errcode = '42501';
      end if;
      select * into v_owner from public.profiles where id = v_owner_id;
      if not found or v_owner.role <> 'Marketing Officer' or v_owner.status <> 'active' then
        raise exception 'The initial owner must be an active Marketing Officer' using errcode = '22023';
      end if;
    end if;

    -- Stored in the existing customer convention: 9-digit national number for Somali.
    v_stored := case when v_canon like '+252%' then substr(v_canon, 5) else v_canon end;
    v_customer_id := 'cust-' || replace(gen_random_uuid()::text, '-', '');

    insert into public.customers (id, name, email, phone, notes, marketing_officer_id, registered_by, status)
    values (v_customer_id, v_name, btrim(coalesce(v_new ->> 'email', '')), v_stored,
            btrim(coalesce(v_new ->> 'notes', '')), v_owner_id, v_actor, 'active');

    if v_owner_id is not null then
      insert into public.customer_ownership_changes (customer_id, customer_name, old_officer_id, old_officer_name,
                                                     new_officer_id, new_officer_name, reason, orders_moved,
                                                     changed_by, changed_by_name)
      values (v_customer_id, v_name, null, '', v_owner_id, v_owner.name,
              'Initial owner set at website-request conversion', '{}', v_actor, v_actor_name);

      insert into public.system_logs (id, severity, category, message, user_id, username, target_id, metadata)
      values ('log-' || replace(gen_random_uuid()::text, '-', ''), 'INFO', 'CUSTOMER',
              format('Customer %s created from %s and assigned to %s', v_customer_id, v_label, v_owner.name),
              v_actor, v_actor_name, v_customer_id,
              jsonb_build_object('source', 'db', 'event', 'website_request_initial_owner', 'requestId', p_request_id,
                                 'customerId', v_customer_id, 'officerId', v_owner_id));
    end if;
  end if;

  -- The only path to orders: the unchanged create_order() with all its rules.
  v_order_id := public.create_order(jsonb_build_object(
    'customerId',      v_customer_id,
    'deliveryNotes',   btrim(coalesce(p_payload ->> 'deliveryNotes', '')),
    'belowCostReason', p_payload ->> 'belowCostReason',
    'items',           v_items));

  update public.order_requests
     set status             = 'converted',
         converted_order_id = v_order_id,
         handled_by         = v_actor,
         status_changed_at  = now(),
         updated_at         = now()
   where id = p_request_id;

  insert into public.order_request_events (request_id, event, from_status, to_status, actor_id, actor_name, order_id, details)
  values (p_request_id, 'converted', 'confirmed', 'converted', v_actor, v_actor_name, v_order_id,
          jsonb_build_object('customerId', v_customer_id, 'newCustomer', v_new_cust,
                             'ownerOfficerId', v_owner_id, 'lines', v_items));

  insert into public.system_logs (id, severity, category, message, user_id, username, target_id, metadata)
  values ('log-' || replace(gen_random_uuid()::text, '-', ''), 'INFO', 'ORDER',
          format('Website request %s converted to order %s (%s customer)', v_label, v_order_id,
                 case when v_new_cust then 'new' else 'existing' end),
          v_actor, v_actor_name, p_request_id::text,
          jsonb_build_object('source', 'db', 'event', 'website_request_converted', 'requestId', p_request_id,
                             'orderId', v_order_id, 'customerId', v_customer_id, 'newCustomer', v_new_cust));
  return v_order_id;
end;
$fn$;

-- ============================================================================
-- 7. VIEW: request lines, legacy header product as line 1
-- ============================================================================

create or replace view public.order_request_lines
with (security_invoker = true) as
select i.request_id, i.line_no, i.product_id, i.product_name, i.quantity, false as legacy
  from public.order_request_items i
union all
select r.id, 1, r.product_id, r.product_name, r.quantity, true
  from public.order_requests r
 where not exists (select 1 from public.order_request_items i where i.request_id = r.id);

-- ============================================================================
-- 8. EXISTING FUNCTIONS CHANGED BY 18 (deployed text + marked edits)
-- ============================================================================

-- @@GRANT_ROLE_PRESET@@

-- @@GUARD_SYSTEM_LOGS_INSERT@@

-- ============================================================================
-- 9. PERMISSION
-- ============================================================================

insert into public.permissions (code, label, category, sort_order)
values ('manage_website_requests', 'Handle website requests', 'Orders', 25)
on conflict (code) do nothing;

insert into public.user_permissions (user_id, permission_code)
select p.id, 'manage_website_requests' from public.profiles p
 where p.role = 'Manager' and p.status = 'active'
on conflict do nothing;

-- ============================================================================
-- 10. RLS
-- ============================================================================

drop policy if exists order_requests_select on public.order_requests;
create policy order_requests_select on public.order_requests
  for select to authenticated using (public.can_access_order_request(assigned_to));
drop policy if exists order_requests_update on public.order_requests;
-- order_requests_insert_public stays until 18c.

alter table public.order_request_items      enable row level security;
alter table public.order_request_notes      enable row level security;
alter table public.order_request_events     enable row level security;
alter table public.website_request_settings enable row level security;

drop policy if exists order_request_items_select on public.order_request_items;
create policy order_request_items_select on public.order_request_items
  for select to authenticated
  using (exists (select 1 from public.order_requests r where r.id = order_request_items.request_id));

drop policy if exists order_request_notes_select on public.order_request_notes;
create policy order_request_notes_select on public.order_request_notes
  for select to authenticated
  using (exists (select 1 from public.order_requests r where r.id = order_request_notes.request_id));

drop policy if exists order_request_events_select on public.order_request_events;
create policy order_request_events_select on public.order_request_events
  for select to authenticated
  using (exists (select 1 from public.order_requests r where r.id = order_request_events.request_id));

drop policy if exists website_request_settings_select on public.website_request_settings;
create policy website_request_settings_select on public.website_request_settings
  for select to authenticated using (public.has_permission('manage_website_requests'));
drop policy if exists website_request_settings_update on public.website_request_settings;
create policy website_request_settings_update on public.website_request_settings
  for update to authenticated using (public.is_super_admin()) with check (public.is_super_admin());

-- ============================================================================
-- 11. GRANTS (Supabase default privileges grant ALL to anon; take it back)
-- ============================================================================

revoke all on public.order_requests from anon;
grant insert on public.order_requests to anon;   -- legacy path, removed by 18c

revoke all on public.order_request_items, public.order_request_notes, public.order_request_events,
              public.website_request_settings, public.order_request_lines from anon, authenticated;
grant select on public.order_request_items, public.order_request_notes, public.order_request_events,
                public.order_request_lines to authenticated;
grant select, update on public.website_request_settings to authenticated;

revoke all on function public.guard_order_request_child()                        from public, anon, authenticated;
revoke all on function public.website_request_settings_stamp()                   from public, anon, authenticated;
revoke all on function public.can_access_order_request(text)                     from public, anon, authenticated;
revoke all on function public.normalize_phone(text, text)                        from public, anon, authenticated;
revoke all on function public.customer_phone_canonical(text)                     from public, anon, authenticated;
revoke all on function public.validate_request_phone(text)                       from public, anon, authenticated;
revoke all on function public.website_request_lock_key(text)                     from public, anon, authenticated;
revoke all on function public.website_request_admission(text, uuid)              from public, anon, authenticated;
revoke all on function public.submit_order_request(jsonb)                        from public, anon, authenticated;
revoke all on function public.order_requests_legacy_admission()                  from public, anon, authenticated;
revoke all on function public.set_order_request_status(uuid, text, text)         from public, anon, authenticated;
revoke all on function public.add_order_request_note(uuid, text)                 from public, anon, authenticated;
revoke all on function public.edit_order_request_note(uuid, text)                from public, anon, authenticated;
revoke all on function public.find_customers_by_phone(uuid, text)                from public, anon, authenticated;
revoke all on function public.convert_website_request(uuid, jsonb)               from public, anon, authenticated;

grant execute on function public.can_access_order_request(text)             to authenticated;   -- evaluated by RLS
grant execute on function public.normalize_phone(text, text)                to authenticated;
grant execute on function public.customer_phone_canonical(text)             to authenticated;
grant execute on function public.submit_order_request(jsonb)                to anon, authenticated;
grant execute on function public.set_order_request_status(uuid, text, text) to authenticated;
grant execute on function public.add_order_request_note(uuid, text)         to authenticated;
grant execute on function public.edit_order_request_note(uuid, text)        to authenticated;
grant execute on function public.find_customers_by_phone(uuid, text)        to authenticated;
grant execute on function public.convert_website_request(uuid, jsonb)       to authenticated;

-- Retired: needs only create_orders and bypasses the new lifecycle.
revoke execute on function public.convert_order_request(uuid, text) from authenticated;

-- ============================================================================
-- 12. REALTIME
-- ============================================================================

do $rt$
begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    raise exception '18b: supabase_realtime publication is missing';
  end if;
  if not exists (select 1 from pg_publication_tables
                  where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'order_requests') then
    alter publication supabase_realtime add table public.order_requests;
  end if;
end
$rt$;

-- ============================================================================
-- 13. POST-CHECK: nothing written to existing requests; every object as designed.
-- ============================================================================

do $post$
declare
  v_changed integer;
  v_lines   integer;
  v_missing text;
begin
  select count(*) into v_changed
    from m18_requests_before b
    left join public.order_requests r on r.id = b.id
   where r.id is null
      or md5(row(r.id, r.customer_name, r.phone, r.organization, r.product_id, r.product_name, r.quantity,
                 r.delivery_location, r.notes, r.status, r.converted_order_id, r.handled_by,
                 r.created_at, r.updated_at)::text) <> b.row_md5;
  if v_changed > 0 then
    raise exception '18b post-check: % existing request(s) changed - aborting', v_changed;
  end if;

  select count(*) into v_lines
    from public.order_request_items i join m18_requests_before b on b.id = i.request_id
   where not exists (select 1 from public.order_request_events e
                      where e.request_id = i.request_id and e.event = 'submitted' and e.source = 'rpc');
  if v_lines > 0 then
    raise exception '18b post-check: % line(s) were written for pre-existing requests - aborting', v_lines;
  end if;

  select string_agg(x, ', ') into v_missing from (
    select 'function ' || f as x from unnest(array[
      'can_access_order_request(text)', 'normalize_phone(text,text)', 'customer_phone_canonical(text)',
      'validate_request_phone(text)', 'website_request_lock_key(text)', 'website_request_admission(text,uuid)',
      'submit_order_request(jsonb)', 'set_order_request_status(uuid,text,text)', 'add_order_request_note(uuid,text)',
      'edit_order_request_note(uuid,text)', 'find_customers_by_phone(uuid,text)', 'convert_website_request(uuid,jsonb)',
      'order_requests_legacy_admission()']) f
     where to_regprocedure('public.' || f) is null
    union all
    select 'volatility ' || p.proname from pg_proc p
     where p.oid in (to_regprocedure('public.website_request_admission(text,uuid)'),
                     to_regprocedure('public.submit_order_request(jsonb)'))
       and p.provolatile <> 'v'
    union all
    select 'anon can ' || priv || ' order_requests' from unnest(array['SELECT', 'UPDATE', 'DELETE']) priv
     where has_table_privilege('anon', 'public.order_requests', priv)
    union all
    select 'anon cannot submit' where not has_function_privilege('anon', 'public.submit_order_request(jsonb)', 'EXECUTE')
    union all
    select 'anon can execute ' || f from unnest(array['website_request_admission(text,uuid)', 'validate_request_phone(text)',
                                                       'convert_website_request(uuid,jsonb)', 'set_order_request_status(uuid,text,text)',
                                                       'find_customers_by_phone(uuid,text)', 'can_access_order_request(text)']) f
     where has_function_privilege('anon', 'public.' || f, 'EXECUTE')
    union all
    select 'authenticated can execute ' || f from unnest(array['website_request_admission(text,uuid)', 'validate_request_phone(text)',
                                                                'convert_order_request(uuid,text)']) f
     where has_function_privilege('authenticated', 'public.' || f, 'EXECUTE')
    union all
    select 'anon can read ' || t from unnest(array['order_request_items', 'order_request_notes', 'order_request_events',
                                                    'website_request_settings', 'order_request_lines']) t
     where has_table_privilege('anon', 'public.' || t, 'SELECT')
    union all
    select 'policy order_requests_update still present' where exists (
      select 1 from pg_policy where polrelid = 'public.order_requests'::regclass and polname = 'order_requests_update')
    union all
    select 'realtime publication' where not exists (
      select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'order_requests')
    union all
    select 'permission row' where not exists (select 1 from public.permissions where code = 'manage_website_requests')
    union all
    select 'settings row' where (select count(*) from public.website_request_settings) <> 1
  ) q;
  if v_missing is not null then
    raise exception '18b post-check failed: % - aborting', v_missing;
  end if;
  raise notice '18b: website request inbox installed; % existing request(s) verified unchanged',
    (select count(*) from m18_requests_before);
end
$post$;

commit;
